sudo: required
services: 
  - docker
env:
  global: 
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # For encrypting the service-account.json file 
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  #download google cloud on our instance and install it
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  #lookup default install dir source the file below
  - source $HOME/google-cloud-sdk/path.bash.inc
  # install kubectl command
  - gcloud components update kubectl
  #Authorization access to the google cloud account
  - gcloud auth activate-service-account --key-file service-account.json
  #add the project name
  - gcloud config set project multi-k8s-282711
  #Add Localtion
  - gcloud config set compute/zone us-east1-b
  # Name of the cluster
  - gcloud container clusters get-credentials mult-cluster
  #provide docker credentials
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  #build test version of multi client image and then our tests inside it
  - docker build -t svarpe/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true svarpe/react-test npm run test

deploy: 
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master 

